-- questao 6:
SELECT 
    c.NOME AS CATEGORIA,
    AVG(p.PRECO) AS PRECO_MEDIO
FROM PRODUTO p
JOIN CATEGORIA c 
    ON p.CODIGO_CATEGORIA = c.CODIGO
GROUP BY c.NOME
HAVING AVG(p.PRECO) > 2000;

-- questao 10:
SELECT 
    p.CODIGO,
    p.NOME,
    COUNT(h.CODIGO) AS TOTAL_ADICOES
FROM HISTORICO_PROD_ADIC_CARRINHO h
JOIN PRODUTO p 
    ON h.CODIGO_PRODUTO = p.CODIGO
GROUP BY p.CODIGO, p.NOME
HAVING COUNT(h.CODIGO) > 5;
