CREATE TABLE FORNECEDOR (
    CODIGO INT PRIMARY KEY,
    HOME_PAGE VARCHAR(100) NOT NULL,
    NOME VARCHAR (100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL, 
    TELEFONE VARCHAR(50) NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    CEP VARCHAR(30) NOT NULL,
    ESTADO VARCHAR (50) NOT NULL ,
    NUMERO VARCHAR (10)NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL
);