CREATE TABLE HIST_VISUALIZACAO_PRODUTO(
    CODIGO_HISTORICO INT, 
    TEMPO_PAGINA INT NOT NULL, 

    CONSTRAINT CK_TEMPO_POSITIVO CHECK (TEMPO_PAGINA>=0),
    CONSTRAINT FK_HIST_VISUALIZACAO_PRODUTO_CODIGO_HISTORICO FOREIGN KEY (CODIGO_HISTORICO)
        REFERENCES HISTORICO(CODIGO),
    CONSTRAINT PK_HIST_VISUALIZACAO_PRODUTO PRIMARY KEY (CODIGO_HISTORICO)
);