CREATE TABLE NOTA_FISCAL (
	CODIGO 				INT PRIMARY KEY,
	CHAVE_DE_ACESSO		CHAR(44) NOT NULL,
	INSCRICAO_ESTADUAL	VARCHAR2(9),
	VALOR_TOTAL			NUMERIC(10,2) NOT NULL,
	SERIE				INT NOT NULL,
	NUMERO				INT NOT NULL,

	CONSTRAINT CK_VALOR_TOTAL_POSITIVO CHECK (VALOR_TOTAL >= 0)
);
