CREATE TABLE PRODUTO (
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PRECO NUMERIC(10,2) NOT NULL,
    DATA_FABRICACAO DATE NOT NULL,
    DESCRICAO VARCHAR(255),
    ESPECIFICACAO VARCHAR(255),
    DATA_VALIDADE DATE NOT NULL,

    CONSTRAINT PRECO_POSITIVO CHECK (PRECO >= 0),
    CONSTRAINT DT_VALIDADE_VALIDA CHECK (DATA_VALIDADE >= DATA_FABRICACAO)
);

CREATE TABLE FOTOS_PRODUTO(
    PRODUTO_CODIGO INT NOT NULL,
    URL VARCHAR(255) NOT NULL,
    CONSTRAINT FK_FOTO_PRODUTO FOREIGN KEY (PRODUTO_CODIGO)
        REFERENCES PRODUTO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT PK_FOTOS_PRODUTO PRIMARY KEY (PRODUTO_CODIGO, URL)
);