CREATE TABLE TRANSPORTADORA(
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(50) NOT NULL,
    SITE VARCHAR(255),
    RUA VARCHAR(255) NOT NULL,
    CEP CHAR(9) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    BAIRRO VARCHAR(255)
);