SELECT DISTINCT f.CODIGO, f.NOME 
FROM FORNECEDOR f, PRODUTO p, CATEGORIA c, FORNECEDOR_FORNECE_PRODUTO ffp
WHERE f.CODIGO = ffp.CODIGO_FORNECEDOR 
  AND p.CODIGO = ffp.CODIGO_PRODUTO 
  AND p.CODIGO_CATEGORIA = c.CODIGO 
  AND c.NOME = 'Material Escolar'

UNION

SELECT f.CODIGO, f.NOME 
FROM FORNECEDOR f
MINUS
SELECT f.CODIGO, f.NOME 
FROM FORNECEDOR f, PRODUTO p, CATEGORIA c, FORNECEDOR_FORNECE_PRODUTO ffp
WHERE f.CODIGO = ffp.CODIGO_FORNECEDOR 
  AND p.CODIGO = ffp.CODIGO_PRODUTO 
  AND p.CODIGO_CATEGORIA = c.CODIGO 
  AND c.NOME = 'Material de Limpeza';