CREATE TABLE PRODUTO_ORDEM_COMPRA(
    COD_PRODUTO INT,
    COD_ORDEM_COMPRA INT,

    CONSTRAINT FK_PRODUTO_ORDEM_COMPRA_COD_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (CODIGO),
    CONSTRAINT FK_PRODUTO_ORDEM_COMPRA_COD_ORDEM_COMPRA FOREIGN KEY (COD_ORDEM_COMPRA) REFERENCES ORDEM_COMPRA (CODIGO)
)