CREATE TABLE TRANSPORTADORA(
    CODIGO INT PRIMARY KEY,
    NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    TELEFONE VARCHAR(50),
    SITE VARCHAR(255),
    RUA VARCHAR(255),
    CEP CHAR(9),
    ESTADO VARCHAR(50),
    NUMERO VARCHAR(20),
    BAIRRO VARCHAR(255)
);