INSERT INTO CLIENTE (CODIGO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, EMAIL, PONTOS, CLIENTE_INDICADOR, RUA, ESTADO, CEP, NUMERO, BAIRRO)
VALUES (1, 'Clara', 'Silva', TO_DATE('1999-05-20','YYYY-MM-DD'), 'FEMININO', 'clara.silva@email.com', 100, NULL, 'Rua A', 'São Paulo', '01000-000', '123', 'Centro');

INSERT INTO CLIENTE (CODIGO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, EMAIL, PONTOS, CLIENTE_INDICADOR, RUA, ESTADO, CEP, NUMERO, BAIRRO)
VALUES (2, 'Lucas', 'Santos', TO_DATE('1995-08-12','YYYY-MM-DD'), 'MASCULINO', 'lucas.santos@email.com', 50, 1, 'Rua B', 'Rio de Janeiro', '20000-000', '456', 'Botafogo');

INSERT INTO CLIENTE (CODIGO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, EMAIL, PONTOS, CLIENTE_INDICADOR, RUA, ESTADO, CEP, NUMERO, BAIRRO)
VALUES (3, 'Maria', 'Oliveira', TO_DATE('2000-01-15','YYYY-MM-DD'), 'FEMININO', 'maria.oliveira@email.com', 75, 1, 'Rua C', 'Minas Gerais', '30100-000', '789', 'Savassi');

INSERT INTO CLIENTE (CODIGO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, EMAIL, PONTOS, CLIENTE_INDICADOR, RUA, ESTADO, CEP, NUMERO, BAIRRO)
VALUES (4, 'Pedro', 'Almeida', TO_DATE('1988-03-22','YYYY-MM-DD'), 'MASCULINO', 'pedro.almeida@email.com', 120, 2, 'Rua D', 'Bahia', '40000-000', '101', 'Barra');

INSERT INTO CLIENTE (CODIGO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, EMAIL, PONTOS, CLIENTE_INDICADOR, RUA, ESTADO, CEP, NUMERO, BAIRRO)
VALUES (5, 'Ana', 'Costa', TO_DATE('1992-11-05','YYYY-MM-DD'), 'FEMININO', 'ana.costa@email.com', 90, NULL, 'Rua E', 'Paraná', '80000-000', '202', 'Centro');

INSERT INTO CLIENTE (CODIGO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, EMAIL, PONTOS, CLIENTE_INDICADOR, RUA, ESTADO, CEP, NUMERO, BAIRRO)
VALUES (6, 'Rafael', 'Pereira', TO_DATE('1997-07-18','YYYY-MM-DD'), 'MASCULINO', 'rafael.pereira@email.com', 60, 5, 'Rua F', 'Santa Catarina', '88000-000', '303', 'Kobrasol');

INSERT INTO CLIENTE (CODIGO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, EMAIL, PONTOS, CLIENTE_INDICADOR, RUA, ESTADO, CEP, NUMERO, BAIRRO)
VALUES (7, 'Carla', 'Fernandes', TO_DATE('2001-09-30','YYYY-MM-DD'), 'FEMININO', 'carla.fernandes@email.com', 40, NULL, 'Rua G', 'Pernambuco', '50000-000', '404', 'Recife Antigo');

INSERT INTO CLIENTE (CODIGO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, EMAIL, PONTOS, CLIENTE_INDICADOR, RUA, ESTADO, CEP, NUMERO, BAIRRO)
VALUES (8, 'Bruno', 'Gomes', TO_DATE('1990-12-10','YYYY-MM-DD'), 'MASCULINO', 'bruno.gomes@email.com', 110, NULL, 'Rua H', 'Ceará', '60000-000', '505', 'Meireles');

INSERT INTO CLIENTE (CODIGO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, EMAIL, PONTOS, CLIENTE_INDICADOR, RUA, ESTADO, CEP, NUMERO, BAIRRO)
VALUES (9, 'Juliana', 'Martins', TO_DATE('1996-04-25','YYYY-MM-DD'), 'FEMININO', 'juliana.martins@email.com', 30, 7, 'Rua I', 'Rio Grande do Sul', '90000-000', '606', 'Moinhos');

INSERT INTO CLIENTE (CODIGO, NOME, SOBRENOME, DATA_NASCIMENTO, SEXO, EMAIL, PONTOS, CLIENTE_INDICADOR, RUA, ESTADO, CEP, NUMERO, BAIRRO)
VALUES (10, 'Felipe', 'Rodrigues', TO_DATE('1993-06-14','YYYY-MM-DD'), 'MASCULINO', 'felipe.rodrigues@email.com', 80, 3, 'Rua J', 'Goiás', '74000-000', '707', 'Setor Oeste');
