CREATE OR REPLACE FUNCTION get_qtd_prox_vencimentos(COD_CD NUMBER)
RETURN NUMBER
IS
DATA_VALIDADE_MAX DATE := SYSDATE + 5;
DATA_PRODUTO PRODUTO.DATA_VALIDADE%TYPE;
CONTADOR NUMBER := 0;
CURSOR produtos IS
    SELECT p.DATA_VALIDADE
    FROM produto p, PROD_ESTOCADO_CENT_DIST pecd
    WHERE COD_CD = pecd.CODIGO_CENTRO_DISTRIBUICAO AND
        pecd.CODIGO_PRODUTO = p.codigo AND
        p.DATA_VALIDADE > SYSDATE AND
        p.DATA_VALIDADE < DATA_VALIDADE_MAX;
BEGIN
    OPEN produtos;
    LOOP
        FETCH produtos INTO DATA_PRODUTO;
        EXIT WHEN produtos%NOTFOUND;
        CONTADOR:=CONTADOR+1;

    END LOOP;
    CLOSE produtos;

    RETURN contador;
END;