CREATE TABLE PRODUTO_CARRINHO (
    QUANTIDADES INT NOT NULL,
    COD_CARRINHO INT,
    COD_PRODUTO INT,
    CONSTRAINT FK_PRODUTO_CARRINHO_CODCARRINHO FOREIGN KEY (COD_CARRINHO) REFERENCES CARRINHO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_PRODUTO_CARRINHO_CODPRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT PK_PRODUTO_CARRINHO PRIMARY KEY(COD_CARRINHO, COD_PRODUTO),
    CONSTRAINT QUANTIDADE_POSITIVA CHECK (QUANTIDADES >= 0)
);