CREATE TABLE CENTRO_DISTRIBUICAO_INVENTARIO(
    COD_PRODUTO INT,
    COD_CENTRO_DISTR INT,
    QUANTIDADE INT NOT NULL,

    CONSTRAINT PK_CENTRO_DISTR_INVENTARIO PRIMARY KEY (COD_PRODUTO, COD_CENTRO_DISTR),
    CONSTRAINT FK_INVENTARIO_PRODUTO FOREIGN KEY (COD_PRODUTO)
        REFERENCES PRODUTO(CODIGO),
    CONSTRAINT FK_INVENTARIO_CENTRO_DISTR FOREIGN KEY (COD_CENTRO_DISTR)
        REFERENCES CENTRO_DISTRIBUICAO(CODIGO),
    CONSTRAINT CK_QUANT_INVENT_POSITIVA CHECK (QUANTIDADE >= 0)
);