CREATE TABLE AVALIACAO_PRODUTO(
    ID_PRODUTO INT,
    ID_ORDEM_COMPRA INT,
    DESCRICAO VARCHAR(255),
    NOTA DECIMAL(4,2) NOT NULL,

    CONSTRAINT CK_AVALIACAO_PRODUTO_NOTA_POSITIVA CHECK (NOTA >=0 AND NOTA <= 10),
    CONSTRAINT PK_AVALIACAO_PRODUTO PRIMARY KEY (ID_PRODUTO,ID_ORDEM_COMPRA),
    CONSTRAINT FK_AVALIACAO_PRODUTO_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (CODIGO),
    CONSTRAINT FK_AVALIACAO_PRODUTO_ID_ORDEM_COMPRA FOREIGN KEY (ID_ORDEM_COMPRA) REFERENCES ORDEM_COMPRA (CODIGO)
)
