CREATE TABLE AVALIACAO_PRODUTO(
    COD_PRODUTO INT,
    COD_ORDEM_COMPRA INT,
    DESCRICAO VARCHAR(255),
    NOTA INT NOT NULL,

    CONSTRAINT CK_AVALIACAO_PRODUTO_NOTA_POSITIVA CHECK (NOTA >=0 AND NOTA <= 5),
    CONSTRAINT PK_AVALIACAO_PRODUTO PRIMARY KEY (COD_PRODUTO,COD_ORDEM_COMPRA),
    CONSTRAINT FK_AVALIACAO_PRODUTO_COD_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (CODIGO),
    CONSTRAINT FK_AVALIACAO_PRODUTO_ID_ORDEM_COMPRA FOREIGN KEY (ID_ORDEM_COMPRA) REFERENCES ORDEM_COMPRA (CODIGO)
);
