CREATE TABLE "ADICAO_PRODUTO_CARRINHO" (
	CODIGO_HISTORICO NUMBER(*,0) NOT NULL ENABLE, 
	CODIGO_PRODUTO NUMBER(*,0) NOT NULL ENABLE, 
	FINALIZOU CHAR(3) NOT NULL ENABLE, 
	 
	CHECK (FINALIZOU IN ('SIM','NAO')) ENABLE, 
	CONSTRAINT "PK_ADICAO_PRODUTO_CARRINHO" PRIMARY KEY ("CODIGO_HISTORICO")

USING INDEX  ENABLE
);

  ALTER TABLE "ADICAO_PRODUTO_CARRINHO" ADD CONSTRAINT "FK_ADICAO_CARRINHO_HIST" FOREIGN KEY ("CODIGO_HISTORICO")
	  REFERENCES "HISTORICO" ("CODIGO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ADICAO_PRODUTO_CARRINHO" ADD CONSTRAINT "FK_ADICAO_CARRINHO_PROD" FOREIGN KEY ("CODIGO_PRODUTO")
	  REFERENCES "PRODUTO" ("CODIGO") ENABLE;
