CREATE TABLE CUPOM_CATEGORIA(
    ID_CUPOM INT,
    ID_CATEGORIA INT, 
    CONSTRAINT FK_CUPOMCATEGRIA_IDCUPOM FOREIGN KEY (ID_CUPOM) REFERENCES CUPOM_DESCONTO(CODIGO),
    CONSTRAINT FK_CUPOMCATEGORIA_IDCATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(CODIGO),
    CONSTRAINT PK_CUPOM_CATEGORIA PRIMARY KEY (ID_CUPOM, ID_CATEGORIA)
);