CREATE TABLE CUPOM_CATEGORIA(
    CODIGO INT,
    COD_CATEGORIA INT, 
    CONSTRAINT FK_CUPOMCATEGRIA_COD_CUPOM FOREIGN KEY (CODIGO) REFERENCES CUPOM_DESCONTO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT FK_CUPOMCATEGORIA_COD_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA(CODIGO) ON DELETE CASCADE,
    CONSTRAINT PK_CUPOM_CATEGORIA PRIMARY KEY (CODIGO, COD_CATEGORIA)
);