CREATE TABLE CUPOM_CATEGORIA(
    ID_CUPOM INT,
    ID_CATEGORIA INT, 
    CONSTRAINT PK_CUPOMCATEGRIA_IDCUPOM FOREIGN KEY (ID_CUPOM) REFERENCES CUPOM_DESCONTO(CODIGO),
    CONSTRAINT PK_CUPOMCATEGORIA_IDCATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(CODIGO)
);