 CREATE TABLE CUPOM_DESCONTO (
	CODIGO NUMBER(*,0), 
	DESCONTO NUMBER(5,2) NOT NULL ENABLE,
 
	CONSTRAINT CK_DESCONTO CHECK (DESCONTO >= 0 AND DESCONTO <=100) ENABLE, 
	PRIMARY KEY (CODIGO)
 
 USING INDEX ENABLE
 );
