CREATE TABLE FORNECIMENTO_PRODUTO(
COD_PRODUTO INT,
COD_FORNECEDOR INT,
CONSTRAINT FK_FORNECIMENTO_COD_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(CODIGO),
CONSTRAINT FK_FORNECIMENTO_COD_FORNECEDOR FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDOR(CODIGO),
CONSTRAINT PK_FORNECIMENTO_PRODUTO PRIMARY KEY (COD_PRODUTO, COD_FORNECEDOR)
);
