CREATE TABLE FORNECIMENTO_PRODUTO(
ID_PRODUTO INT,
ID_FORNECEDOR INT,
CONSTRAINT FK_FORNECIMENTO_COD_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(CODIGO),
CONSTRAINT FK_FORNECIMENTO_COD_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(CODIGO),
CONSTRAINT PK_FORNECIMENTO_PRODUTO PRIMARY KEY (ID_PRODUTO, ID_FORNECEDOR)
);
