CREATE TABLE HISTORICO (
    CODIGO INT PRIMARY KEY,
    DATA TIMESTAMP DEFAULT SYSTIMESTAMP,
    COD_CLIENTE INT,
    COD_PRODUTO INT,

    CONSTRAINT FK_HIST_PRODUTO FOREIGN KEY (COD_PRODUTO)
        REFERENCES PRODUTO(CODIGO),
    CONSTRAINT FK_HIST_CLIENTE FOREIGN KEY (COD_CLIENTE)
        REFERENCES CLIENTE(CODIGO)
);