CREATE TABLE HIST_ADICAO_PRODUTO_CARRINHO(
    CODIGO_HISTORICO INT, 
    FINALIZOU CHAR(1) NOT NULL, 

    CONSTRAINT CK_COMPRA_FINALIZADA CHECK (FINALIZOU IN ('S','N')),
    CONSTRAINT FK_HIST_ADICAO_CARRINHO FOREIGN KEY (CODIGO_HISTORICO)
        REFERENCES HISTORICO(CODIGO),
    CONSTRAINT PK_ADICAO_CARRINHO PRIMARY KEY (CODIGO_HISTORICO)
);
