CREATE TABLE NOTA_FISCAL (
	CODIGO 				NUMBER(*,0),
	CHAVE_DE_ACESSO		CHAR(44) NOT NULL ENABLE,
	INSCRICAO_ESTADUAL	VARCHAR2(9),
	VALOR_TOTAL			NUMBER(10,2) NOT NULL ENABLE,
	SERIE				NUMBER(3,0) NOT NULL ENABLE,
	NUMERO				NUMBER(9,0) NOT NULL ENABLE,

	CONSTRAINT CK_VALOR_TOTAL_POSITIVO CHECK (VALOR_TOTAL >= 0) ENABLE,
	PRIMARY KEY (CODIGO)

USING INDEX ENABLE
);
