CREATE TABLE ORDEM_COMPRA( 
    CODIGO INT PRIMARY KEY, 
    DATA TIMESTAMP NOT NULL,
    STATUS VARCHAR(255) NOT NULL, 
    DESCONTO DECIMAL(5,2), 
    FRETE DECIMAL(10,2) NOT NULL, 
    RUA VARCHAR(255) NOT NULL, 
    CEP CHAR(9) NOT NULL, 
    ESTADO VARCHAR(50) NOT NULL, 
    NUMERO VARCHAR(20) NOT NULL, 
    BAIRRO VARCHAR(255) NOT NULL, 
    COD_TRANSPORTADORA INT, 
    COD_NOTAFISCAL INT, 
    COD_CLIENTE INT,

    ADD CONSTRAINT CK_ORDEM_COMPRA_DESCONTO_POSITIVO CHECK (DESCONTO >= 0 AND DESCONTO <= 100)
);