CREATE TABLE ORDEM_COMPRA( 
    CODIGO              INT PRIMARY KEY, 
    DATA_COMPRA         TIMESTAMP NOT NULL,
    STATUS_COMPRA       VARCHAR(255) NOT NULL, 
    DESCONTO            DECIMAL(5,2), 
    FRETE               DECIMAL(10,2) NOT NULL, 
    RUA                 VARCHAR(255) NOT NULL, 
    CEP                 CHAR(9) NOT NULL, 
    ESTADO              VARCHAR(50) NOT NULL, 
    NUMERO              VARCHAR(20) NOT NULL, 
    BAIRRO              VARCHAR(255) NOT NULL, 
    COD_TRANSPORTADORA  INT NOT NULL, 
    COD_NOTAFISCAL      INT NOT NULL, 
    COD_CLIENTE         INT NOT NULL, 
    CONSTRAINT FK_NOTA_FISCAL_ORDEM_COMPRA FOREIGN KEY (COD_NOTAFISCAL)
        REFERENCES NOTA_FISCAL(CODIGO),
    CONSTRAINT FK_ORDEM_COMPRA_COD_CLIENTE FOREIGN KEY (COD_CLIENTE) 
        REFERENCES CLIENTE(CODIGO)
        ON DELETE CASCADE,
    CONSTRAINT FK_ORDEM_COMPRA_COD_TRANSPORTADORA FOREIGN KEY (COD_TRANSPORTADORA) 
        REFERENCES TRANSPORTADORA(CODIGO),
    CONSTRAINT CK_ORDEM_COMPRA_DESCONTO_POSITIVO CHECK (DESCONTO >= 0 AND DESCONTO <= 100),
    CONSTRAINT CK_STATUS_ORDEM_COMPRA CHECK (STATUS_COMPRA IN ('Aguardando Pagamento', 'Em separação', 'Em transporte', 'Finalizada'))
);