CREATE TABLE PRODUTO_CARRINHO (
    QUANTIDADES INT,
    ID_CARRINHO INT,
    ID_PRODUTO INT,
    CONSTRAINT FK_PRODUTO_CARRINHO_IDCARRINHO FOREIGN KEY (ID_CARRINHO) REFERENCES CARRINHO(CODIGO),
    CONSTRAINT FK_PRODUTO_CARRINHO_IDPRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(CODIGO),
    CONSTRAINT PK_PRODUTO_CARRINHO PRIMARY KEY(ID_CARRINHO, ID_PRODUTO),
    CONSTRAINT QUANTIDADE_POSITIVA CHECK (QUANTIDADES >= 0)
);